name: Docker build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: false
        type: string
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-classic-amd64:
    name: build docker images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: openvino
            context: build-main
            file: Dockerfile.openvino
            platforms: linux/amd64
            suffix: -openvino

          - image: cuda
            context: build-main
            file: Dockerfile.cuda
            platforms: linux/amd64
            suffix: -cuda

          - image: classic
            context: build-main
            file: Dockerfile
            platforms: linux/amd64,linux/arm64

          - image: noml
            context: build-noml
            file: Dockerfile
            platforms: linux/amd64,linux/arm64
            suffix: -noml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set tags
        id: tags
        run: |
          echo "build_date=$(date +'%Y-%m-%dT%H:%M:%S%:z')" >> $GITHUB_ENV

      - name: Create Dockerfile from template
        run: python3 render_templates.py

      - name: Generate docker image tags
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/immich
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'workflow_dispatch' }},suffix=${{ matrix.suffix }}
            type=ref,event=branch,enable=${{ github.event_name != 'workflow_dispatch' }}
            type=ref,event=pr
            type=ref,event=tag
            type=raw,value=${{ inputs.version }},enable=${{ github.event_name == 'workflow_dispatch' }},suffix=${{ matrix.suffix }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push docker images
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          provenance: false # prevent unknown architecture
          file: ${{ matrix.context }}/${{ matrix.file }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name == 'workflow_dispatch' }}
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          build-args: |
            IMMICH_VERSION=${{ inputs.version }}
