name: External trigger
on:
  schedule:
    - cron: "*/20 * * * *"

permissions:
  contents: read
  pages: write

jobs:
  check_new_version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.check_version.outputs.new_version }}
      immich_version: ${{ steps.check_version.outputs.immich_version }}
      current_version: ${{ steps.check_version.outputs.current_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if new version is available
        id: check_version
        run: |
          current_version=$(curl -sL https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases/latest | jq -r '.tag_name')
          immich_version=$(curl -sL https://api.github.com/repos/immich-app/immich/releases/latest | jq -r '.tag_name')
          if [ "$current_version" != "$immich_version" ]; then
            if git tag | grep -q "^$immich_version$"; then
              echo "Tag '$immich_version' exists."
            else
              echo "New immich version ($immich_version) detected."
              echo "current_version=$current_version" >> $GITHUB_OUTPUT
              echo "immich_version=$immich_version" >> $GITHUB_OUTPUT
              echo "new_version=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          else
            echo "Immich version ($immich_version) already exists"
          fi
          echo "new_version=false" >> $GITHUB_OUTPUT

  create_new_version:
    if: ${{ needs.check_new_version.outputs.new_version == 'true' }}
    runs-on: ubuntu-latest
    needs: [check_new_version]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Create new release for AIO
        run: |
          git config --global user.email "49699333+dependabot[bot]@users.noreply.github.com"
          git config --global user.name "dependabot[bot]"
          git tag "${{ needs.check_new_version.outputs.immich_version }}"
          git push --tags
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            --data "{\"tag_name\": \"${{ needs.check_new_version.outputs.immich_version }}\",
                \"target_commitish\": \"main\",
                \"name\": \"${{ needs.check_new_version.outputs.immich_version }}\",
                \"generate_release_notes\": true,
                \"body\": \"Read Immich release notes [here](https://github.com/immich-app/immich/releases/tag/${{ needs.check_new_version.outputs.immich_version }})\",
                \"draft\": false,
                \"prerelease\": false}" \
            "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases"

      - name: Trigger workflow
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            --data '{"event_type": "trigger_build", "client_payload": {"message": "'"${{ needs.check_new_version.outputs.immich_version }}"'"}}' \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/dispatches
