name: Test suites

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-format:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install formatters
        run: |
          pip install ruff==0.3.2
          npm i prettier@3.2.5

      - name: Run python linter
        run: ruff check **.py

      - name: Run python formatter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "24.2.0"

      - name: Run formatter
        run: npx prettier --check .

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: "run"
