name: lint and format

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "version"
        required: false
        type: string
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-format:
    name: linter and formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install shell linter
        run: sudo apt-get install shellcheck

      - name: Install python formatter and linter
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Run linter
        run: ruff check **.py

      - name: Run formatter
        run: black --check **.py

      - name: Run shell linter
        run: find . -type f -name "run" -exec shellcheck {} +
