name: Run tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-format:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install python formatter and linter
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Run linter
        run: ruff check **.py

      - name: Run formatter
        run: black --check **.py

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: 'run'
