name: Run tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-format:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install python formatter
        run: pip install ruff

      - name: Run linter
        run: ruff check **.py

      - uses: psf/black@stable
        with:
          options: "--check --verbose"

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: 'run'
